services:

  backend:
    build: 
      context: ../../
      dockerfile: deployment/docker/backend.Dockerfile
    container_name: backend-server
    runtime: nvidia
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8000/docs"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  
  postgres:
    image: postgres:17
    container_name: postgres-server
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped


  pg_admin:
    image: dpage/pgadmin4
    container_name: pgadmin-server
    environtment:
      PGADMIN_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5000:5000"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped


  neo4j:
    image: neo4j:5.26-community
    container_name: neo4j-server
    ports:
      - "7474:7474" # HTTP Port Endpoint
      - "7687:7687" # BOLT Port Endpoint
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_memory_heap_initial__size=8G
      - NEO4J_server_memory_heap_max__size=8G
      - NEO4J_server_memory_pagecache_size=8G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null -q http://localhost:7474 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped


volumes:
  pg_data:
    name: compfest_pgdata
    external: true
  pgadmin_data:
    name: compfest_pgadmin_data
    external: true
  neo4j_data:
    name: compfest_neo4j_data
    external: true
  neo4j_logs:
    name: compfest_neo4j_logs
    external: true
  neo4j_import:
    name: compfest_neo4j_import
    external: true
  neo4j_plugins:
    name: compfest_neo4j_plugins
    external: true