blank_issues_enabled: false
contact_links:
  - name: Team Discussion
    url: https://github.com/ReubenZSTechs/UI-Compfest-AIC/discussions
    about: Ask general questions or discuss ideas before opening an issue
